# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
import:
 - ~/.config/alacritty/themes/themes/github_dimmed.yaml
 - ~/.config/alacritty/window.yaml

window:
  decorations: buttonless

font:
  normal:
    family: Hack Nerd Font Mono
  bold:
    family: Hack Nerd Font Mono
  italic:
    family: Hack Nerd Font Mono
  size: 14.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

key_bindings:
  - { key: V,        mods: Command,         action: Paste                        }
  - { key: C,        mods: Command,         action: Copy                         }
  - { key: Q,        mods: Command,         action: Quit                         }
  - { key: W,        mods: Command,         action: Quit                         }
  - { key: Left,     mods: Command,         chars: "\x1bOH"                      }
  - { key: Right,    mods: Command,         chars: "\x1bOF"                      }
