import = ["~/.config/alacritty/themes/themes/github_dark.toml", "~/.config/alacritty/window.toml"]

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font Mono"

[font.bold]
family = "Hack Nerd Font Mono"

[font.italic]
family = "Hack Nerd Font Mono"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mods = "Command"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
