env:
  TERM: xterm-256color

# Font configuration (changes require restart)
font:
  normal:
    family: MesloLGS NF
  bold:
    family: MesloLGS NF
  italic:
    family: MesloLGS NF
  size: 14.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  # Thin stroke font rendering (macOS only)
  use_thin_strokes: true


selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

key_bindings:
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Left,     mods: Command, chars: "\x1bOH"                      }
  - { key: Right,    mods: Command, chars: "\x1bOF"                      }
