# ~/.config/ghostty/config

theme = GitHub Dark Dimmed
cursor-style = block
shell-integration = zsh
shell-integration-features = no-cursor

# 폰트 설정
font-family = "Hack Nerd Font Mono"
font-family = "D2CodingLigature Nerd Font Mono"
font-size = 14

# 윈도우 설정
macos-option-as-alt = true
macos-titlebar-style = tabs

# 선택 설정
copy-on-select = clipboard

# # 커서 이동 (Home/End)
keybind = cmd+left=text:\x1bOH
keybind = cmd+right=text:\x1bOF
